name: diretoria 

on: 

  push:
   branches: [ "main" ]
  pull_request:
   branches: [ "main" ]

  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version
      
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Step 3 Execute collection
        run: newman run ./Diretoria.json -e ./Academy.json -g ./globals.json -r htmlextra --reporter-htmlextra-export ./result_diretoria/report.html

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./result_diretoria/**